### ISSUE TITLE
Cannot read property 'replaceCallPaths' of undefined

### ISSUE THREAD

**Issue by lolmaus** [intercom/ember-computed-template-string#10]
```
Cannot read property 'replaceCallPaths' of undefined
TypeError: Cannot read property 'replaceCallPaths' of undefined
    at ComputedTemplateStringTransform (/home/lolmaus/Code/launchpad2/node_modules/ember-computed-template-string/plugins/computed-template-string-transform.js:5:43)
    at CoreObject.module.exports.included (/home/lolmaus/Code/launchpad2/node_modules/ember-computed-template-string/index.js:16:38)
    at CoreObject.superWrapper [as included] (/home/lolmaus/Code/launchpad2/node_modules/core-object/lib/assign-properties.js:32:18)
    at EmberApp.<anonymous> (/home/lolmaus/Code/launchpad2/node_modules/ember-cli/lib/broccoli/ember-app.js:468:15)
    at Array.filter (native)
    at EmberApp._notifyAddonIncluded (/home/lolmaus/Code/launchpad2/node_modules/ember-cli/lib/broccoli/ember-app.js:463:45)
    at new EmberApp (/home/lolmaus/Code/launchpad2/node_modules/ember-cli/lib/broccoli/ember-app.js:138:8)
    at module.exports (/home/lolmaus/Code/launchpad2/ember-cli-build.js:8:15)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/home/lolmaus/Code/launchpad2/node_modules/ember-cli/lib/models/builder.js:74:19)
    at CoreObject.module.exports.Task.extend.init (/home/lolmaus/Code/launchpad2/node_modules/ember-cli/lib/models/builder.js:54:10)

Process finished with exit code 1
```

Immediate issue is [here](https://github.com/intercom/ember-computed-template-string/blob/master/plugins/computed-template-string-transform.js#L5).

The problem is that `ComputedTemplateStringTransform` function [is called](https://github.com/intercom/ember-computed-template-string/blob/master/index.js#L16) with `app.options.emberComputedTemplateString`, but `emberComputedTemplateString` property is never set and thus is undefined.

**Comment by lolmaus** [comment]
Ember stack version 2.7.0
